package amt-composer:simple;

interface host-goodies-types {
    record rec {
        a: u32,
        b: s8
    }
}

interface host-goodies {
    use host-goodies-types.{rec};

    print: func(r: rec);
    passthru: func(r: rec) -> rec;
}

interface guest-main {
    run: func() -> bool;
    print-vec: func(v:list<u8>) -> list<u8>;
}

interface inter-guest-types {
    record rec {
        a: u32,
        b: u32,
    }
}

interface inter-guest {
    use inter-guest-types.{rec};

    add: func(r: rec) -> u32;
    passthru: func(r: rec) -> rec;
}
